config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'home#index'

  root 'home#index'

  resources :reservations
  resources :books
  resources :categories
  resources :librarians
  resources :librarian
  devise_for :librarian, path: 'routeto'
  resources :users
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reservations
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.all
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def librarian_params
      params.require(:librarian).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name%>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.email_field :email%>
      </div>

      <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>

      <div class="field">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
      </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>

app/views/librarians/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
  transition: background-color .5s;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #122c5a;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: white;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: white;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%=link_to "Livros",books_path %>
  <%=link_to "Categorias",categories_path %>
  <%=link_to "Reservas",reservations_path %>
  <%=link_to "Bibliotecários",librarians_path %>
  <%=link_to "Usuários",users_path %>
  <%=link_to "Autores",authors_path %>
  <br>
  <br>
  <%=link_to "Sair", destroy_librarian_session_path, method: :delete %>
</div>

<div id="main">
<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>
<div class="container">
<div class="row justify-content-center">
<div class="col text-center">
<p id="notice"><%= notice %></p>

<h1>Librarians</h1>


</div>
</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.name %></td>
        <td><%= librarian.email %></td>
        <td><%= librarian.password %></td>
        <td><%= librarian.password_confirmation %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Librarian', new_librarian_path %>

<%= render partial:"/partials/voltar" %>
<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
  document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
  document.body.style.backgroundColor = "white";
}
</script>
   
</body>
</html> 

app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Back', librarians_path %>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @librarian.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @librarian.email %>
</p>

<%= link_to 'Edit', edit_librarian_path(@librarian) %> |
<%= link_to 'Back', librarians_path %>